# Perceptron
The Perceptron class in scikit-learn is a linear classification algorithm that is built on top of the Stochastic Gradient Descent (SGD) approach. It's primarily used for binary and multi-class classification tasks and implements a variant of the Perceptron algorithm, which is an early form of a neural network. Here's a breakdown of its functionality and usage:

### Key Concepts:
- Classification Algorithm: The Perceptron is a linear classifier, meaning it tries to find a hyperplane that separates the data into different classes.
- SGD-Based Implementation: It's essentially a simplified version of SGDClassifier, where specific loss and learning rate settings make it equivalent to the Perceptron algorithm.

class sklearn.linear_model.Perceptron(*, penalty=None, alpha=0.0001, l1_ratio=0.15, fit_intercept=True, max_iter=1000, tol=0.001, shuffle=True, verbose=0, eta0=1.0, n_jobs=None, random_state=0, early_stopping=False, validation_fraction=0.1, n_iter_no_change=5, class_weight=None, warm_start=False)

In [1]:
import numpy as np

In [2]:
def unit_step_function(x):
    return np.where(x>0,1,0)

In [3]:
class Perceptron:
    def __init__(self,learning_rate=0.01,n_iters=1000):
        self.lr=learning_rate
        self.n_iters=n_iters
        self.activation_func=unit_step_function
        self.bias=None
        self.weights=None

    def fit(self,X,y):
        n_samples,n_features=X.shape
        self.weights=np.zeros(n_features)
        self.bias=0
        y=np.where(y>0,1,0)
        for i in range(self.n_iters):
            for idx,x_i in enumerate(X):
                z=np.dot(x_i,self.weights)+self.bias
                y_pred=self.activation_func(z)
                self.weights+=self.lr*(y[idx]-y_pred)*x_i
                self.bias+=self.lr*(y[idx]-y_pred)
                
    def predict(self,X):
        z=np.dot(X,self.weights)+self.bias
        return self.activation_func(z)

In [4]:
from sklearn import datasets
X,y=datasets.make_blobs(n_samples=1000,n_features=2,centers=2,cluster_std=1.05,random_state=40)

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1234)

In [6]:
clf=Perceptron()
clf.fit(X_train,y_train)
predictions=clf.predict(X_test)
predictions

array([0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1])

In [7]:
y_test

array([0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1])

In [8]:
def accuracy(y_true,y_pred):
    c0,c1,acc0,acc1=0,0,0,0
    for i in range(len(y_true)):
        if y_true[i]==0:
            c0+=1
            if y_true[i]==y_pred[i]:
                acc0+=1
        else:
            c1+=1
            if y_true[i]==y_pred[i]:
                acc1+=1
                
    return [acc0/c0 , acc1/c1]
accuracy(y_test,predictions)

[1.0, 1.0]

In [9]:
import pandas as pd

In [10]:
df=pd.read_csv("diabetes.csv")
X=df.drop(columns=["Outcome"])
y=df["Outcome"]

In [11]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1234)
X_train=np.array(X_train)
y_train=np.array(y_train)
y_test=np.array(y_test)
x_test=np.array(X_test)

In [12]:
clf=Perceptron()
clf.fit(X_train,y_train)
predictions=clf.predict(X_test)
predictions

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [13]:
y_test=np.where(y_test<=0,0,1)
y_test

array([0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0])

In [14]:
accuracy(y_test,predictions)

[0.9797979797979798, 0.0]

### Parameters:
- penalty: Regularization term to prevent overfitting. Options include:
<b>'l2'</b> for Ridge regression.
<b>'l1'</b> for Lasso regression.
<b>'elasticnet'</b> for a combination of both.
- alpha: Regularization strength multiplier for the penalty term (default 0.0001).
- fit_intercept: Whether to calculate the intercept for the model. If False, data should be centered.
- max_iter: Maximum number of epochs, i.e., how many times the algorithm will pass through the training data.
- tol: The stopping criterion for the optimization.
- shuffle: Whether to shuffle the training data after each epoch.
- random_state: Controls the shuffling and other random number generation processes for reproducibility.
- early_stopping: Stops training early if the validation score does not improve.
- warm_start: Reuses the solution of the previous fit to continue training from where it left off.
- class_weight: Balances classes by assigning higher weights to minority classes.
- n_jobs: Number of CPU cores to use for computation (in multi-class classification problems).

In [15]:
from sklearn.linear_model import Perceptron

# Initialize the Perceptron model
clf = Perceptron()

clf.fit(X_train,y_train)
predictions=clf.predict(X_test)
predictions

C:\Users\gyanb\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but Perceptron was fitted without feature names
  warnings.warn(


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
      dtype=int64)

In [16]:
y_test

array([0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0])

In [17]:
accuracy(y_test,predictions)

[0.9292929292929293, 0.0]

### Methods:
- fit(X, y): Trains the perceptron model on the dataset X and the corresponding labels y.
- predict(X): Predicts the class labels for the data X.
- partial_fit(X, y): Performs one epoch of SGD on the provided data. Useful when handling large datasets.
- score(X, y): Returns the mean accuracy of the predictions on a test dataset.
- decision_function(X): Provides confidence scores for the predictions.

### Attributes:
- coef_: The weight coefficients for the features.
- intercept_: The bias term (intercept).
- n_iter_: The number of iterations the model has run.

### Practical Example:
- from sklearn.datasets import load_digits<br>
from sklearn.linear_model import Perceptron

- Load digits dataset<br>
X, y = load_digits(return_X_y=True)

- Initialize the Perceptron model<br>
clf = Perceptron(tol=1e-3, random_state=0)

- Train the model<br>
clf.fit(X, y)

- Evaluate the accuracy<br>
score = clf.score(X, y)<br>
print(f"Accuracy: {score}")

- The Perceptron algorithm is sensitive to feature scaling. You may want to standardize your dataset before using it.
- In practice, more sophisticated algorithms such as Support Vector Machines (SVMs) or Logistic Regression often perform better for linear classification tasks due to additional hyperparameter tuning and optimization options.